### ISSUE TITLE
Translation suggestions

### ISSUE THREAD

**Issue by remi-sc** [NicolasTurpin/Touhou-Gensou-Mahjong-4N---ENGLISH-translation#2]
Those are things that I noticed when going through the diffs:

1. GFX/multi/net_agreement.png
    > Online Machmaking is made via DNA softwares servers

    "is made via" doesn't seem to fit - I would think "uses" would fit better
    > name, and

    comma is unnecessary

2. S/actor/player/ui.lua
    > Abortion

    Not entirely sure but I think you meant the noun "abort". "abortion" may be correct but I don't think it is commonly used in this meaning
    >  2 Hans are required

    This is very debatable but I think in this case "2 Han" instead of "2 Hans" would be better. At least I can't really find this "hans"  form used much on the internet. Including EMA, ESPML or World Riichi Championship Rules rulebooks. And when I played in person we didn't change the form (although it wasn't in english)
    I see this same "hans" form in following files:
```
    S/STATS/TAKUS/KOURINDOU.LUA
    S/STATS/ACHIEVEMENT.CSV
    S/STATS/CHARACTERS.CSV
    S/STATS/CHARACTERS.CSV
    S/STATS/CHARACTERS.CSV
    S/ACTOR/PLAYER/UI.LUA
    S/SCENE/GAME/01_SETTING.LUA
    S/SCENE/INFORMATION.LUA
```

    
3. s/scene/multi/create.lua
    > No password will be set when acception quick matches

    accepting

4. S/stats/takus/kirisametei.lua
    I think you are using "characters" instead of sticking to "numbered tiles" here (for manzu)
    > "Bambous"

    AFAIK bamboo does not have a separate plural form

5. S/stats/takus/moriya_honden.lua
    > each dragon tiles contains an aka-dora

    this doesn't sound right. Maybe "dragon tiles contain a single aka-dora each" ?
    
6. S/stats/takus/tengu.lua
    > Each rounds

    IMO "Every round" would be correct here

**Comment by NicolasTurpin** [comment]
Thanks a lot !!!!
I'll modify it as you said !

**Comment by NicolasTurpin** [comment]
For Kirisametei (Marisa's Room)

The rule is that :
round one : manzu tiles contains 9 red doras, one for each number
round two : instead of manzu, souzu tiles are now getting one red-dora of each number
round three : pinzu tiles...
round four : terminal and honnors....

You weren't sure of the translation in itself or was my english too strange to understand it well ? x)

As for my choice of words, I'm using "characters" for Manzu tiles and "numbered tiles" for non-Jihai tiles (every 1-9 tiles all series included)

If you think of a better way to say it in english I'll take it ^^

**Comment by NicolasTurpin** [comment]
What do you think would sound better ?

Kyuushu Kyuhai Abort ?
Kyuushu Kyuhai Reset ?
Kyuushu Kyuhai Redeal ?

**Comment by remi-sc** [comment]
I would say "Kyuushu Kyuhai Abort"
From what I see most pages I could find use either variations of "aborted hand" or "abortive draw" terms.
> https://riichi.wiki/Tochuu_ryuukyoku
> https://en.wikipedia.org/wiki/Japanese_Mahjong#Abortive_draws

**Comment by remi-sc** [comment]
> You weren't sure of the translation in itself or was my english too strange to understand it well ? x)

Now after reading it again I see that I misunderstood the meaning of the rule.
It isn't really that clear. I interpreted a "serie" as 1-9 tiles, while intepreting both "characters" and "numbered tiles" as manzu.
AFAIK in mahjong terminology a "suit" is more common than "serie"/"series"

now It's:
> Each numbered tiles of a serie contains an aka-dora. The serie in question depend of the turn:\nCharacters > Bambous > Circles > Honors & Terminals

There is a few more things to note:
- Also: After taking a second look there I think "serie" isn't a word that is used anymore - "series" is much more common.
- if the rule is about numbered suits then why would "Honors & Terminals" appear here
- Is the rule rotating every "turn" or every "round"?

Depending on how it actually is I would suggest changing it to sometihng like this:
> All numbered tiles of a single suit contains an aka-dora. This suit rotates every round: Characters > Bamboo > Circles

**Comment by remi-sc** [comment]
Or if the "Honors & Terminals"  also get a round after all then I would suggest this:
(I assume that Terminals don't really apply because those are 1,9 which would be included in normal suits)

> Every round a suit is given an aka-dora to each of it's tiles. The suit rotates every round: Characters > Bamboo > Circles > Honors

**Comment by NicolasTurpin** [comment]
You're right ! When playing on other games the word "suit" was way more used than "serie" ! I'm replacing everything !

The 4th round actually contains aka-dora for Honnor AND Terminal tiles, they are used twice here ^^
But yeah I don't know why I precised "numbered tiles" as the Honnors are included... let's remove it, it will be clearer haha

And it rotates every round, each time the seats are turning (so to say : if a renchan occurs, the "dora-suit" stays the same)

**Comment by NicolasTurpin** [comment]
> _It's hard to find a precise and short translation here..._

Yeah xD that was the issue for most characters when our alphabet is taking so much space haha

>Every round a suit is given an aka-dora to each of it's tiles. The suit rotates every round: Characters > Bamboo > Circles > Terminals & Honors

This sounds great !

**Comment by remi-sc** [comment]
The imperfection with "suit" is that it usually seems to only be used in regards to manzu/pinzu/souzu while "honors" are just "honors".

So "Every round a suit is given an aka-dora to each of it's tiles" isn't really ideal. but I don;t really have a better idea at the moment.

**Comment by NicolasTurpin** [comment]
Hopefully all characters refering to "suits" are not including honors so there's only this table

We could use "group" as honor could, to some extend, be considered a "serie" but [honors + terminals] not that much x)

**Comment by NicolasTurpin** [comment]
I fixed everything ! ^^

And btw : hope you like my little addition of showing the speel-gauge speed on each character and table description ;3

**Comment by NicolasTurpin** [comment]
Ooooh okay Kirisametei is even messier than I thought :
It doesn't rotates every times the seats are changing, it changes depending on the kyoku number.
That doesn't change ANYTHING even the slightest in 4 players... but in 3 players, East4 / South4 doesn't exist so the "Honor & Terminal are dora" round never happens.

Until I finish translatinh the status effects icons and the Training mode I'll find a nice way to say it x)

**Comment by remi-sc** [comment]
Great to hear, in that case I am closing this issue since I don't really have anything to add at this moment.
After you release it I will check it out and open new suggestion thread if I find anything.
